#!/usr/bin/env node

require.paths.unshift('src');
try {
    require('parser');
} catch(e) {
    console.log('parser module not found. Must run `make` first.');
    return;
}

require('compile').main();
